### ISSUE TITLE
Error when starting bridge

### ISSUE THREAD

**Issue by SohumB** [matrix-hacks/matrix-puppet-hangouts#1]
Hey! This is a neat project and I wanted to try it out :) After some initial finagling with hangups being unable to find the auth_code (see https://github.com/tdryer/hangups/issues/269 ), I got the hangups command line client working, so I think everything on that end is working fine.

But I'm getting this error on the bridge itself:

```
SyncApi.sync: starting with sync token null
Got push rules
synced
started hangups child
Matrix-side listening on port 8091
/home/sohum/matrix-puppet-hangouts/node_modules/matrix-js-sdk/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof pri
ntErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"=
==typeof a);return a},"undefined"!=
                                                                                                                ^

SyntaxError: Unexpected token H in JSON at position 0
    at JSON.parse (<anonymous>)
    at Pipe.channel.onread (internal/child_process.js:462:28)

npm ERR! Linux 2.6.32-042stab120.16
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! matrix-puppet-hangouts@0.0.1 start: `DEBUG=matrix-puppet:* node index.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the matrix-puppet-hangouts@0.0.1 start script 'DEBUG=matrix-puppet:* node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the matrix-puppet-hangouts package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=matrix-puppet:* node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs matrix-puppet-hangouts
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls matrix-puppet-hangouts
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sohum/matrix-puppet-hangouts/npm-debug.log
```

`npm-debug.log` contains this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle matrix-puppet-hangouts@0.0.1~prestart: matrix-puppet-hangouts@0.0.1
6 silly lifecycle matrix-puppet-hangouts@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle matrix-puppet-hangouts@0.0.1~start: matrix-puppet-hangouts@0.0.1
8 verbose lifecycle matrix-puppet-hangouts@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle matrix-puppet-hangouts@0.0.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/sohum/matrix-puppet-hangouts/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle matrix-puppet-hangouts@0.0.1~start: CWD: /home/sohum/matrix-puppet-hangouts
11 silly lifecycle matrix-puppet-hangouts@0.0.1~start: Args: [ '-c', 'DEBUG=matrix-puppet:* node index.js' ]
12 silly lifecycle matrix-puppet-hangouts@0.0.1~start: Returned: code: 7  signal: null
13 info lifecycle matrix-puppet-hangouts@0.0.1~start: Failed to exec start script
14 verbose stack Error: matrix-puppet-hangouts@0.0.1 start: `DEBUG=matrix-puppet:* node index.js`
14 verbose stack Exit status 7
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid matrix-puppet-hangouts@0.0.1
16 verbose cwd /home/sohum/matrix-puppet-hangouts
17 error Linux 2.6.32-042stab120.16
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error matrix-puppet-hangouts@0.0.1 start: `DEBUG=matrix-puppet:* node index.js`
22 error Exit status 7
23 error Failed at the matrix-puppet-hangouts@0.0.1 start script 'DEBUG=matrix-puppet:* node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the matrix-puppet-hangouts package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     DEBUG=matrix-puppet:* node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs matrix-puppet-hangouts
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls matrix-puppet-hangouts
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by AndrewJDR** [comment]
Hello, I just added some additional debug output. Can you please try pulling down the latest version, run it with `npm start`, then report the output here? Specifically I'll be looking for a line like this:
```
verbose:matrix-puppet:hangouts:client got message from hangups before JSON.parse() <important output will be here>
```

**Comment by SohumB** [comment]
`got message from hangups before JSON.parse(): Hangouts login failed. Either you didn't log in yet, or your refresh token expired.
Please log in with --login-and-save-token`

Okay, so whatever finagling I did didn't actually work; I'll dig into that. Thanks!

**Comment by SohumB** [comment]
OH. I just figured it out. I was running the bridge via systemd, so it was running as root and thus not seeing the refresh token in ~/.cache/hangups. Thanks for the help in figuring this out!
