### ISSUE TITLE
"please implement sendReadReceiptAsPuppetToThirdPartyRoomWithId"

### ISSUE THREAD

**Issue by vpzomtrrfrt** [matrix-hacks/matrix-puppet-hangouts#17]
I can't seem to send messages, and this error shows up in the logs, may be related?
```
puppet_1  | Unhandled rejection Error: please implement sendReadReceiptAsPuppetToThirdPartyRoomWithId
puppet_1  |     at App.sendReadReceiptAsPuppetToThirdPartyRoomWithId (/usr/src/matrix-puppet-hangouts/node_modules/matrix-puppet-bridge/src/base.js:168:27)
puppet_1  |     at MatrixClient.client.on (/usr/src/matrix-puppet-hangouts/node_modules/matrix-puppet-bridge/src/puppet.js:65:35)
puppet_1  |     at emitTwo (events.js:126:13)
puppet_1  |     at MatrixClient.emit (events.js:214:7)
puppet_1  |     at Room.<anonymous> (/usr/src/matrix-puppet-hangouts/node_modules/matrix-js-sdk/lib/reemit.js:58:35)
puppet_1  |     at emitTwo (events.js:126:13)
puppet_1  |     at Room.emit (events.js:214:7)
puppet_1  |     at Room.addReceipt (/usr/src/matrix-puppet-hangouts
```

**Comment by AndrewJDR** [comment]
That message is a red herring. The most likely cause of not being able to send messages is that your homeserver is not communicating with the hangouts bridge at all.

Double check that:
1. You've installed the hangouts registration yaml file into the homeserver's directory and added the corresponding entry into your homeserver.yaml
2. That the port that you've specified is correct in your registration file
3. That you did the registration process against the homeserver.
etc

**Comment by AndrewJDR** [comment]
If all that fails, search in the homeserver log for the ip or hostname you're using for your hangouts bridge instance (the one specified in your hangouts registration yaml file). That should hopefully give you some clues.

**Comment by vpzomtrrfrt** [comment]
Apparently synapse doesn't like underscores in hostnames.  Changing that resolved my issue, but it seems like fixing this error would still be worth doing
