### ISSUE TITLE
Authorization code cookie not found (javascript needed error in lynx)

### ISSUE THREAD

**Issue by kalon33** [matrix-hacks/matrix-puppet-hangouts#18]
I got the following error trying to get the cookie:
```
Traceback (most recent call last):
  File "hangups_client.py", line 252, in <module>
    run_example(listen_events)
  File "hangups_client.py", line 56, in run_example
    cookies = hangups.auth.get_auth_stdin(args.token_path)
  File "/usr/local/lib/python3.6/dist-packages/hangups/auth.py", line 188, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/usr/local/lib/python3.6/dist-packages/hangups/auth.py", line 166, in get_auth
    session, credentials_prompt
  File "/usr/local/lib/python3.6/dist-packages/hangups/auth.py", line 296, in _get_authorization_code
    raise GoogleAuthError('Authorization code cookie not found')
hangups.auth.GoogleAuthError: Authorization code cookie not found
```
Trying to connect with lynx, Google says that it needs Javascript for security reasons to continue.

How to fix or workaround this?

**Comment by ghost** [comment]
Furthermore, the instructions appear to be out of date; the current version of `hangups` has no `--manual` option:

```
(synapse) util% hangups -v                                                                 
hangups 0.4.5                                                                              
(synapse) util% hangups --manual                                                           
usage: hangups [-h] [--token-path TOKEN_PATH] [--date-format DATE_FORMAT]                  
...
               [--col-tab-background-bg COL_TAB_BACKGROUND_BG]                             
hangups: error: unrecognized arguments: --manual                                           
```

Logging in from a new, anonymous browser window on a different computer does not prompt for SMS, and doesn't change the result that @kalon33 reported.
