### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by SohumB** [matrix-hacks/matrix-puppet-hangouts#3]
Oh, this is fun.

```
ERROR:asyncio:Exception in callback _on_message_sent() at hangups_client.py:183
handle: ) at hangups_client.py:183>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "hangups_client.py", line 186, in _on_message_sent
    future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/hangups/conversation.py", line 277, in send_message
    yield from self._client.send_chat_message(request)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 529, in send_chat_message
    send_chat_message_request, response)
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 338, in _pb_request
    request_pb.SerializeToString()
  File "/usr/local/lib/python3.4/dist-packages/hangups/client.py", line 396, in _base_request
    data=data, connector=self._connector
  File "/usr/local/lib/python3.4/dist-packages/hangups/http_utils.py", line 36, in fetch
    ), CONNECT_TIMEOUT)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 466, in request
    read_until_eof=read_until_eof)
  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 105, in request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```

As far as I can tell, it occurred when an incoming voice call happened. Additionally, this then caused the bridge to get stuck, but not crash—so my watchdog doesn't restart it and messages didn't get through indefinitely until I restarted it myself.

**Comment by AndrewJDR** [comment]
Ok, if you pull down the latest, 8387e8a, there's broader exception catching in that part of the code now. So hopefully this won't crash so badly in the future, but it should still print out an error to the Hangouts status room.

FWIW, I placed a call to the google voice number associated with my google account and hangups didn't seem to receive any kind of event within hangups, so I'm not sure that was the catalyst for the error. That said, if you can try to reproduce it by calling yourself, I'd appreciate it.

**Comment by tdryer** [comment]
That exception is known issue in hangups (see https://github.com/tdryer/hangups/issues/288).

**Comment by AndrewJDR** [comment]
Thanks @tdryer !

**Comment by SohumB** [comment]
I haven't been able to replicate this in the past month, so I'm gonna go ahead and close it :)
