### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by LHeffJr** [matrix-hacks/matrix-puppet-hangouts#36]
When I try registering the service I get the following:

matrix-puppet-hangouts$ node index.js -r -u "http://localhost:8090"
/opt/matrix-puppet-hangouts/node_modules/matrix-puppet-bridge/src/base.js:709
    } catch {
            ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/opt/matrix-puppet-hangouts/node_modules/matrix-puppet-bridge/index.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:654:30)

Here is my node version:
node --version
v9.11.2

I found a similar issue here and tried following the instrucitons there but was unablke to solve my issue.
https://github.com/matrix-hacks/matrix-puppet-hangouts/issues/26

**Comment by LHeffJr** [comment]
Please disregard. I upgraded my version of node to 12.x and the issue was resolved.
