### ISSUE TITLE
Unknown verification code input

### ISSUE THREAD

**Issue by sauyon** [matrix-hacks/matrix-puppet-hangouts#6]
I get the following output when using Google's notification-based 2FA:

```
root@sio:~/matrix-puppet-hangouts# ./hangups_client.py --login-and-save-token
Sign in with your Google account:
Email: me@sauyon.com
Password: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/hangups/auth.py", line 158, in get_auth
    raise GoogleAuthError("Refresh token not found")
hangups.auth.GoogleAuthError: Refresh token not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hangups_client.py", line 240, in <module>
    run_example(listen_events)
  File "./hangups_client.py", line 55, in run_example
    cookies = hangups.auth.get_auth_stdin(args.token_path)
  File "/usr/local/lib/python3.5/dist-packages/hangups/auth.py", line 186, in get_auth_stdin
    return get_auth(CredentialsPrompt(), refresh_token_cache)
  File "/usr/local/lib/python3.5/dist-packages/hangups/auth.py", line 164, in get_auth
    session, credentials_prompt
  File "/usr/local/lib/python3.5/dist-packages/hangups/auth.py", line 280, in _get_authorization_code
    raise GoogleAuthError('Unknown verification code input')
hangups.auth.GoogleAuthError: Unknown verification code input
```

**Comment by NickHu** [comment]
This is hangups
https://github.com/tdryer/hangups/issues/270
